CREATE TABLE HOST
(
    ID VARCHAR(24) PRIMARY KEY,
    NAME VARCHAR(64),
    EMAIL VARCHAR(32),
    PASSWORD VARCHAR(64),
    COURSE_ID VARCHAR(12)
);

CREATE TABLE CLIENT
(
    ID VARCHAR(24) PRIMARY KEY,
    NAME VARCHAR(64),
    EMAIL VARCHAR(32),
    PASSWORD VARCHAR(64)
);


CREATE TABLE TEMP
(
    CID,HID
)